//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Domain.MainModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Option()
        {
            this.SYS_Authorization = new HashSet<SYS_Authorization>();
            this.SYS_DetailOption = new HashSet<SYS_DetailOption>();
            this.SYS_Option1 = new HashSet<SYS_Option>();
        }
    
        public short OptionId { get; set; }
        public byte ApplicationId { get; set; }
        public Nullable<short> ParentId { get; set; }
        public string Name { get; set; }
        public string Tooltip { get; set; }
        public byte Sequence { get; set; }
        public string ViewClass { get; set; }
        public string ViewType { get; set; }
        public string Icon { get; set; }
        public bool Leaf { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Authorization> SYS_Authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_DetailOption> SYS_DetailOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Option> SYS_Option1 { get; set; }
        public virtual SYS_Option SYS_Option2 { get; set; }
        public virtual SYS_Application SYS_Application { get; set; }
    }
}
