//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Domain.MainModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_WorkSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_WorkSpace()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.SYS_Company = new HashSet<SYS_Company>();
            this.SYS_DetailWorkSpace = new HashSet<SYS_DetailWorkSpace>();
        }
    
        public int WorkSpaceId { get; set; }
        public byte WorkSpaceTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Domain { get; set; }
        public byte MonthsTest { get; set; }
        public short MaxUsers { get; set; }
        public decimal PricePerUser { get; set; }
        public byte MaxCompanies { get; set; }
        public decimal PricePerCompany { get; set; }
        public decimal Discount { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Company> SYS_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_DetailWorkSpace> SYS_DetailWorkSpace { get; set; }
        public virtual SYS_WorkSpaceType SYS_WorkSpaceType { get; set; }
    }
}
