//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Domain.MainModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UserCompany
    {
        public string UserId { get; set; }
        public byte CompanyId { get; set; }
        public bool Principal { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
    }
}
