//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Domain.MainModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Authorization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Authorization()
        {
            this.SYS_DetailAuthorization = new HashSet<SYS_DetailAuthorization>();
        }
    
        public string UserId { get; set; }
        public short OptionId { get; set; }
        public byte CompanyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string UserRegistration { get; set; }
        public string UserModification { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
        public virtual SYS_Option SYS_Option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_DetailAuthorization> SYS_DetailAuthorization { get; set; }
    }
}
