//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Domain.MainModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Company()
        {
            this.SYS_Authorization = new HashSet<SYS_Authorization>();
            this.SYS_UserCompany = new HashSet<SYS_UserCompany>();
        }
    
        public byte CompanyId { get; set; }
        public int WorkSpaceId { get; set; }
        public string Code { get; set; }
        public string BusinessName { get; set; }
        public string AlternateCode { get; set; }
        public bool Active { get; set; }
        public bool Canceled { get; set; }
        public string UserRegistration { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Authorization> SYS_Authorization { get; set; }
        public virtual SYS_WorkSpace SYS_WorkSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_UserCompany> SYS_UserCompany { get; set; }
    }
}
