//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Domain.MainModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Application()
        {
            this.SYS_DetailWorkSpace = new HashSet<SYS_DetailWorkSpace>();
            this.SYS_Option = new HashSet<SYS_Option>();
        }
    
        public byte ApplicationId { get; set; }
        public byte ModuleId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Tooltip { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string HostName { get; set; }
        public string HostUri { get; set; }
        public string PathName { get; set; }
        public string PathUri { get; set; }
        public string Icon { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual SYS_Module SYS_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_DetailWorkSpace> SYS_DetailWorkSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Option> SYS_Option { get; set; }
    }
}
