//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatSolution.Infrastructure.MainModule.Context
{
    using CatSolution.Domain.MainModule.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainContext : DbContext
    {
        public MainContext()
            : base("name=MainContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<SYS_Authorization> SYS_Authorization { get; set; }
        public virtual DbSet<SYS_Company> SYS_Company { get; set; }
        public virtual DbSet<SYS_DetailAuthorization> SYS_DetailAuthorization { get; set; }
        public virtual DbSet<SYS_DetailOption> SYS_DetailOption { get; set; }
        public virtual DbSet<SYS_DetailWorkSpace> SYS_DetailWorkSpace { get; set; }
        public virtual DbSet<SYS_Option> SYS_Option { get; set; }
        public virtual DbSet<SYS_UserCompany> SYS_UserCompany { get; set; }
        public virtual DbSet<SYS_WorkSpace> SYS_WorkSpace { get; set; }
        public virtual DbSet<SYS_WorkSpaceType> SYS_WorkSpaceType { get; set; }
        public virtual DbSet<SYS_Application> SYS_Application { get; set; }
        public virtual DbSet<SYS_Module> SYS_Module { get; set; }
    }
}
